### PR TITLE
3.4.1 release

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by kghbln** [comment]
@JeroenDeDauw  Got ya. No tweet :(

**Comment by JeroenDeDauw** [comment]
huh?

**Comment by kghbln** [comment]
yeah

**Comment by JeroenDeDauw** [comment]
confoosed

**Comment by kghbln** [comment]
Hey there is no tweet about the release of SM 3.4 also telling that this one will be the last ....

**Comment by JeroenDeDauw** [comment]
https://twitter.com/JeroenDeDauw/status/779117986833719296

**Comment by kghbln** [comment]
Sorry, Twitter and Hootsuid are currently broken. So I cannot like or retweet either way. Still, thanks for the tweet. :)

**Pull request merged**
