### PR TITLE
Fix query with record type coordinates

### PR DESCRIPTION
**Pull request by mwjames**
### Setup and configuration

- SMW version: any SMW version
- MW version: 1.27+
- DB (MySQL etc.): MariaDB
- SM: master

### Issue

http://sandbox.semantic-mediawiki.org/wiki/CoordinatesAndRecordValue

### CODE REVIEW

**Comment by mwjames** [comment]
While testing (something different yet orthogonal core change), I encountered that coordinates and the `RecordValue` currently don't work together in a query.

**Comment by mwjames** [comment]
Tests are failing because someone played with the CI setup (I know it worked the last time I made a PR!).

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1

    - Installation request for mediawiki/semantic-maps dev-master -> satisfiable by mediawiki/semantic-maps[dev-master].

    - mediawiki/semantic-maps dev-master requires mediawiki/maps ~3.8@dev -> satisfiable by mediawiki/maps[3.8.x-dev] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by JeroenDeDauw** [comment]
CI should work after https://github.com/JeroenDeDauw/Maps/pull/220

**Comment by JeroenDeDauw** [comment]
Thanks!

**Pull request merged**
