### PR TITLE
Simplify QueryPrinter registration

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Another attempt to fix the mysterious OpenLayers bug... though looking at the sandbox, it appears to have been fixed already! \o/ @kghbln

### CODE REVIEW

**Comment by kghbln** [comment]
>  though looking at the sandbox

?

**Comment by JeroenDeDauw** [comment]
117241668_b0bc62928c

**Comment by kghbln** [comment]
No, but admittedly I did only sleep two hours tonight, so things are deteriorating at my end. Just 
proceed-cats-kitten-kitty-pic-picture-funny-lolcat-cute-fun-lovely-photo-images as YodaCat would say.

**Comment by JeroenDeDauw** [comment]
http://pastebin.com/HA58HsBz

**Comment by JeroenDeDauw** [comment]
Going to merge this after the release as this does not improve anything for users and might break things not detected by the tests

**Pull request merged**
