### PR TITLE
Update INSTALL.md

### PR DESCRIPTION
**Pull request by kghbln**

### CODE REVIEW

**Comment by kghbln** [comment]
@JeroenDeDauw Perhaps something to merge prior to tagging 3.4.1

**Comment by JeroenDeDauw** [comment]
Well sure... though likely there will be no 3.5

**Comment by kghbln** [comment]
> Well sure... though likely there will be no 3.5 

Indeed but this would require redoing it "completely". So this is to be seen as the illusion of more to come. :)

**Comment by JeroenDeDauw** [comment]
infinite_sketch

**Pull request merged**
