### PR TITLE
[Do Not Merge] use smw.api for ajax requests

### PR DESCRIPTION
**Pull request by PeterTheOne**
Use smw.api for ajax requests.

Before merge: 
- [ ] There need be `dataItem` in javascript for coordinates. see: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1822
- [ ] https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1821

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Maps should not depend on SMW. Even if you can avoid the code dependency, you are still adding a conceptually linked concept there, which is only needed here in Semantic Maps.

How about adding such a thing to Semantic Maps and translating the Maps objects before sending them to the SMW API?

I'm unclear on what the goal of using the SMW API is though.

**Comment by PeterTheOne** [comment]
> Maps should not depend on SMW. Even if you can avoid the code dependency, you are still adding a conceptually linked concept there, which is only needed here in Semantic Maps.

Ups, my bad.. apparently I still sometimes get confused by all the dependencies of extensions.

> How about adding such a thing to Semantic Maps..

yes

> I'm unclear on what the goal of using the SMW API is though.

First we were using the jquery ajax function directly, smw.api for example also has caching.

**Comment by JeroenDeDauw** [comment]
So the goal is increasing performance and decreasing server load?

I'm curious where this caching is done. Client side? Or is the smw.api thing poking the server side API in such a way caching is done there?

@mwjames is this appropriate use of the smw.api? Do you think it makes sense to use here?

**Comment by PeterTheOne** [comment]
> So the goal is increasing performance and decreasing server load?

My goal was to make use of code that is already there and tested etc.

> I'm curious where this caching is done. Client side? Or is the smw.api thing poking the server side API in such a way caching is done there?

Yes it's client side, have a look at https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/res/smw/api/ext.smw.api.js. It is comparable to client side caching in WhatsNearby https://github.com/SemanticMediaWiki/WhatsNearby/blob/50c9ac8eb3154c4a05628d2412143b8ce2ee4918/res/ext.whats.nearby.js.

**Comment by mwjames** [comment]
> @mwjames is this appropriate use of the smw.api? Do you think it makes sense to use here?

Depends on what you want to do with it. The only real advantage (if at all) is that an api request returns  on object that resembles to some part the DI object in SMW. So instead of doing `hasOwnProperty` calls all over the place you can use an expressive function name. Whether this presents any actual value or not, lies in the eye of the beholder.

> Yes it's client side, have a look a ... comparable to client side caching in WhatsNearby

Yes, both use caching but the difference is that smw.api uses localStorage (because at the time of its writing that was the only real "thing" available).

WhatsNearby and SummaryCards are a bit smarter in a sense that they use the indexedDB (if available otherwise forage switches back to localStorage) and is async to the process of loading data (which is nature of all web-DB solutions).

Reason for using the indexdDB is that, if you need space especially in case of language dependent storage solutions then indexdDB is the only real alternative.

image

Well, Mozilla's forage does all the hard labour, `onoi.blobstore` just reduces the interface to a simple set, get with time eviction.

[0] https://github.com/onoi/shared-resources/blob/master/res/onoi.blobstore.js
[1] https://github.com/SemanticMediaWiki/SummaryCards/blob/master/res/ext.suc.cards.js#L387-L391

**Comment by JeroenDeDauw** [comment]
Needs rebase

**Comment by PeterTheOne** [comment]
I did a rebase. Now depends on https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1821 and still there needs be dataItem in javascript for coordinates.

**Comment by JeroenDeDauw** [comment]
If you want to continue with this, please submit a new PR against the Maps extension.

**Pull request closed without merging**
