### PR TITLE
fix error in ajax compoundquery detection

### PR DESCRIPTION
**Pull request by PeterTheOne**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Non-compound queries can contain this symbol no? Ping @kghbln @mwjames

**Comment by kghbln** [comment]
I do not think so, at least I am not aware and never used it if it surprisingly does.

**Comment by JeroenDeDauw** [comment]
Can't you do a query that contains `;` as normal text, ie `[[Has some text::foo;bar]]`, where `foo;bar` is a text value?

**Comment by JeroenDeDauw** [comment]
Huh, why did I not ping @yaronkoren, he's the authority on this topic

**Comment by kghbln** [comment]
> Can't you do a query that contains `;`

Yes, as part of a value it is possible. I thought you meant some query syntax

**Comment by PeterTheOne** [comment]
The compound_query detection is not perfect, looking for `;` outside of square brackets `[]` should be better. But looking only for `|` in this case is definitely wrong.

**Comment by mwjames** [comment]
I'm not entirely sure about the context but a query condition can contain `;` and depending on the type is interpret in a certain way. An example can found at \[0] (== match all statements with any value and a provenance date not earlier than 2000), also please consult the record type documentation for further help.

[0] http://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Requ%C3%AAter&q=[[Has+population%3A%3A%3F%3B%3E2000]]+&p=format%3Dbroadtable%2Flink%3Dall%2Fheaders%3Dshow%2Fsearchlabel%3D-26hellip-3B-20autres-20r%C3%A9sultats%2Fclass%3Dsortable-20wikitable-20smwtable&po=%3FHas+population%0A&eq=no

**Comment by yaronkoren** [comment]
Certainly, checking for ';' seems to be a _better_ check than '|', if I understand the code correctly (did this code ever work before)? I would hope that there's a less hacky way to determine whether it's a regular or compound query, though - maybe pass that in as a parameter? I don't understand how the current SM Ajax stuff is structured, though.

**Comment by JeroenDeDauw** [comment]
> did this code ever work before)?

Not correctly. Then again, it has not been released yet.

> maybe pass that in as a parameter

Yeah, that's also what I'm thinking might be better, though I suspect I already brought this up during review of the original code.

**Comment by PeterTheOne** [comment]
Btw. https://github.com/SemanticMediaWiki/SemanticCompoundQueries itself does similar (still better) splitting (not detection) of queries https://github.com/SemanticMediaWiki/SemanticCompoundQueries/blob/master/SCQ_QueryProcessor.php#L136 .

**Comment by yaronkoren** [comment]
Splitting based on characters - once you already know it's a compound query - seems better than figuring out whether it's a compound query based on characters.

**Comment by JeroenDeDauw** [comment]
This is a blocker for the next release https://github.com/SemanticMediaWiki/SemanticMaps/issues/76, as it introduces a regression over the previous one. Removing the compound query support until after the release would solve that. (Of course implementing it in a way that does not have the regression would be nicer, though presumably that is more work.)

**Pull request merged**
